version: "3.9"

services:
  frontend:
    build: ./numer/
    ports:
      - "9999:3000"
    volumes:
      - ./numer:/app
      - /app/node_modules
      - /app/build
    depends_on:
      - backend
  backend:
    build: ./backend
    ports:
      - "1234:1234"
    volumes:
      - ./backend:/app
      - /app/node_modules
