swagger: "2.0"
info:
  version: "1.0.0"
  title: "Composite Trapezoidal Rule API"
  description: "Calculates the definite integral of a given equation using the composite trapezoidal rule"
host: "example.com"
basePath: "/api"
schemes:
  - "http"
paths:
/caltrap:
    post:
      summary: "Calculate the definite integral using the composite trapezoidal rule"
      consumes:
        - "application/json"
      produces:
        - "application/json"
      parameters:
        - in: body
          name: equation
          description: "The equation to integrate in string format. Example: 'x^2 + 2x + 1'"
          required: true
          schema:
            type: object
            properties:
              equation:
                type: string
              xlower:
                type: number
              xupper:
                type: number
              n:
                type: integer
      responses:
        200:
          description: "The result of the integral calculation"
          schema:
            type: object
            properties:
              result:
                type: number
